### ISSUE TITLE
The framework version is not correct

### ISSUE THREAD

**Issue by jang675953** [networknt/light-example-4j#106]
https://github.com/networknt/light-example-4j/blob/2131f94cdaefa55de6e58f2529bdd79258896231/routing/pom.xml#L15

The version should be 1.6.3-SNAPSHOT

**Comment by stevehu** [comment]
We have light-bot to upgrade all examples for every release but this example was too old with `version.framework` instead of `version.light-4j` and the light-bot regex-replace cannot find it to upgrade to the latest version. I have updated the pom.xml with all the latest dependencies and made some configuration change for 1.6.3. I also updated the README.md to clearly state the purpose of this example and build/test process. Thanks a lot for raising this issue.

**Comment by stevehu** [comment]
I have added this example for the light-bot version-upgrade so that it will be upgraded by our pipeline during the release. 

https://github.com/networknt/light-config-test/issues/173

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The framework version is not correct](https://trello.com/c/h9pANzF2/242-the-framework-version-is-not-correct)

**Comment by jang675953** [comment]
ok,no thanks.



------------------ 原始邮件 ------------------
发件人: "Steve Hu"<notifications@github.com>; 
发送时间: 2019年5月25日(星期六) 晚上10:43
收件人: "networknt/light-example-4j"<light-example-4j@noreply.github.com>; 
抄送: "675953827"<675953827@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [networknt/light-example-4j] The framework version is not correct(#106)




 The framework version is not correct
 
&mdash;
