### ISSUE TITLE
Database examples are missing from repository

### ISSUE THREAD

**Issue by hansjorg** [networknt/light-example-4j#29]
The documentation refers to some database examples, but they're missing from the repository.

They can be restored from git history with the following:

git checkout 2bd8e8c335376bdc5a9ffa5f605d5f0df2915327 -- database

Seems like they need to be upgraded to the most recent version of light-4j. I could take a look at this if you want.

**Comment by stevehu** [comment]
@hansjorg Yes. There were a database example that supports Mysql, Postgres and Oracle and it might be lost during refactoring. We used to support Restful services only and now we have graphql and rpc based services and all examples and tutorials need to be reorged accordingly. I would be great if you could restore it and upgrade to the latest framework version. Thanks a lot for your help.

**Comment by stevehu** [comment]
@hansjorg I look at the database example and realized that there are a lot of changes since it was created. For example, the version of the framework, config files and light-codegen. It might be easier for me to redo it. Now the code is checked in at https://github.com/networknt/light-example-4j/tree/master/rest/database
and the tutorial has been updated at https://networknt.github.io/light-rest-4j/tutorial/database/

Could you please review if you have time? Thanks.

**Comment by stevehu** [comment]
Let's leave this issue open and use it to ensure that we change the database table to static one instead of dynamic insert 10K data. H2 doesn't support it and the test case won't be executed successfully.
